name = "billing-app"
main = "src/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 4200

[triggers]
crons = ["0 10 * * *", "0 11 * * *"]

[[kv_namespaces]]
binding = "DATA_STORE"
id = "d7c76fb2819f47a3bf7a53c72fa642eb"
