name = "billing-app"
main = "src/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 4200

[[kv_namespaces]]
binding = "DATA_STORE"
id = "aa95a191a3ca475ead0c8c7108db09c1"
