name = "billing-app"
main = "src/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 4200

[[kv_namespaces]]
binding = "DATA_STORE"
id = "8b746b1f95aa44f9972ffc24ae71f7fc"
